### ISSUE TITLE
只有POST和GIT上传和下载呢？

### ISSUE THREAD

**Issue by WuXiaoTu** [jezzmemo/JJNetwork#2]
只有POST和GIT上传和下载呢？

**Comment by jezzmemo** [comment]
你的问题是我现在只有POST和GET吧，没有上传和下载吧。

最近我会考虑进入，上传的功能，下载这个功能可能短时间内是不会加的，因为下载是一个相对比较重，而且相对较复杂和需求多变的，所以建议可以引入专业的下载模块.

**Comment by WuXiaoTu** [comment]
好的，持续关注。。。

**Comment by jezzmemo** [comment]
@WuXiaoTu 我已经添加了上传功能，可以尝试下，有问题随时交流
