### ISSUE TITLE
一个页面多个请求的解决方案

### ISSUE THREAD

**Issue by AlmostSir777** [jezzmemo/JJNetwork#3]
楼主，一个页面多个请求难道写多个request API？

**Comment by jezzmemo** [comment]
按照当前的设计是这样的，每个URL的request都是一个request file,我明白你的问题，你的意思是这样会写很多，是不是太多了，是有这个缺点，但是从维护和功能的单一性来说，这就是单独写的有点，所以这个缺点不算什么。
@VaeXnn
